#!/usr/bin/env bash
# Regenerate the @rommel/proto TypeScript client from proto/schemas/.
# Outputs to proto/clients/ts/src/ (gitignored). Idempotent.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROTO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SCHEMAS_DIR="$PROTO_DIR/schemas"
OUT_DIR="$PROTO_DIR/clients/ts/src"

# json-schema-to-typescript pinned to a major version. Pinned tools = reproducible CI.
J2TS_VERSION="^15"

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

# Walk all *.json schemas, mirror directory structure under src/.
# Each schema becomes one .ts file; index.ts re-exports the lot.
generated_files=()
while IFS= read -r -d '' schema; do
  rel="${schema#$SCHEMAS_DIR/}"
  out="$OUT_DIR/${rel%.json}.ts"
  mkdir -p "$(dirname "$out")"
  NODE_NO_WARNINGS=1 npx --yes "json-schema-to-typescript@$J2TS_VERSION" \
    --input "$schema" \
    --output "$out" \
    --no-additionalProperties \
    --unknownAny >/dev/null
  generated_files+=("${rel%.json}")
done < <(find "$SCHEMAS_DIR" -name "*.json" -type f -print0 | LC_ALL=C sort -z)

# Build a deterministic index.ts that re-exports everything.
{
  echo "// AUTO-GENERATED by proto/codegen/ts.sh — do not edit."
  echo "// Source: proto/schemas/"
  echo ""
  for f in "${generated_files[@]}"; do
    # ts module spec: relative path with no extension, leading ./
    echo "export * from \"./$f\";"
  done
} > "$OUT_DIR/index.ts"

echo "ts: regenerated ${#generated_files[@]} schemas → $OUT_DIR"
